# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/mayfly/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),mayfly)

$(call add-radio-file-sha1-checked,radio/abl.img,659f03910ea40499ad2de11f944a7121ae45cc4e)
$(call add-radio-file-sha1-checked,radio/aop.img,c9917c94a654778762f47af1bd1c2c5cb4514130)
$(call add-radio-file-sha1-checked,radio/aop_config.img,6e90a43b11346c4da258bf246b264aa6445fe3f0)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,46bfd923323a7b284af157643110de5b0ab6700d)
$(call add-radio-file-sha1-checked,radio/cpucp.img,71c95cb6f30cc1ff07d8cf4d3fb81cd59cfcce18)
$(call add-radio-file-sha1-checked,radio/devcfg.img,231672fc47251444b16ee83b176828bbda519f3a)
$(call add-radio-file-sha1-checked,radio/dsp.img,0ff8e8b0948bde7aacc930090c5fa43d349ebe8b)
$(call add-radio-file-sha1-checked,radio/featenabler.img,c78a78a544b92285d78942ef5865a80ff96c6972)
$(call add-radio-file-sha1-checked,radio/hyp.img,7cffe485e2ce518919a4765162c129f36b9abfc4)
$(call add-radio-file-sha1-checked,radio/imagefv.img,e77a6caeb152ca466934504804f1d1319b7e1812)
$(call add-radio-file-sha1-checked,radio/keymaster.img,32ccf6169a34bcc5656ca33f2ceced0f6c26e64e)
$(call add-radio-file-sha1-checked,radio/modem.img,58b95d1e4244d689e08d604746ae2c286bff960e)
$(call add-radio-file-sha1-checked,radio/qupfw.img,0ce57bc10dda047abcd46fa09916c625306b488c)
$(call add-radio-file-sha1-checked,radio/shrm.img,778afb30b1b34726fb6bfe20e96a4f50c8cfd153)
$(call add-radio-file-sha1-checked,radio/tz.img,be13407c79775eb6b24ecbd9bb69ec588d8f59d1)
$(call add-radio-file-sha1-checked,radio/uefi.img,13e6e2d4b586f92639809367783ec75aeeb21f5b)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,31eec4fdc16b267312522067a7928a1b7f97fb26)
$(call add-radio-file-sha1-checked,radio/vm-bootsys.img,e3dcbc83beca8544d635d7f25ad59c568b8e1f94)
$(call add-radio-file-sha1-checked,radio/xbl.img,99c57c9c5af7ec00f862cd09e6636671cb405ecb)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,c206394ffa50ace34308f9423c8345a014815f5f)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,3e19cb02cd3f942c44798a765bdd4f8059fcea3a)

endif
